### PR TITLE
Initial attempt at fixing the `t` helper prefix. Fixes #6.

### LINKED ISSUE #6: Breaks `t('.something')`? 😭
It looks like the magic of `t('.something')` is broken because the `yield` that causes it to execute is in a different view. This is pretty sad, TBH. 

For example, in `app/views/some_class/_index.html.erb`: 

```
<%= render 'shared/box' do |p| %>
  <% p.content_for :title do %>
    <%= t(".contexts.something.header") %>
  <% end %>

  <% p.content_for :description do %>
    <%= t(".contexts.something.description") %>
  <% end %>
<% end %>
```

Yields:

```
translation missing: en.shared.box.contexts.something.header
```

It should have been:

```
en.some_class.index.contexts.something.header
```

### PR DESCRIPTION
**Pull request by andrewculver**

### CODE REVIEW

**Comment by andrewculver** [comment]
@domchristie If we could also figure out how to wrap this around wherever the initial block is yielded to, then it would work for the root level content you like to do as well.

**Comment by andrewculver** [comment]
@domchristie Any objection to merging this in, even as a WIP? I'm already benefitting from this in my named content areas, so would be nice to have in the packaged gem vs. bundling from my local copy.

**Comment by domchristie** [comment]
I _think_ this will break content_for without a block and is account_controller? part of your app’s code?

Thinking more generally, I wonder if adding a callback API would provide a solution to both this and the options_for issue. For example, if we had before_capture, after_capture, before_render, and after_render, developers could hook into the lifecycle and customise the behaviour. It would probably require a custom class that inherits from Partial, but it could provide a path to solving these problems we don’t realise exist yet!—I think I’m concerned that there’ll been more cases like this, that we’re not aware of, and with this approach, we’d end up overriding a lot of helpers. 

I hope that makes sense!

**Comment by andrewculver** [comment]
Ha, yes, sorry, that bled in when I copied and pasted from my local app. I'll clean that up. I feel like if we start going down the route of callbacks, we're losing something about the simplicity and "native-y" feeling. I also think that `t` is pretty unique in providing this specific type of magic. Can we think of any other examples of helpers that reflect on the file they're being executed in this way? At first blush, I can't.

**Comment by domchristie** [comment]
Hmm, I still don't think this will work for cases like:

```erb
<%# app/views/posts/index.html.erb %>
<%= render 'card' do |p| %>
  <% p.content_for :heading, t(.greeting) %>
<% end %>
```
Because the proposed solution relying on `content_for` being given a block :/

I can't think of any other methods like `t` but there's always something! 😬 

If you do decide to merge, overriding [`translate`](https://api.rubyonrails.org/classes/AbstractController/Translation.html#method-i-translate) might be preferable. This _should_ handle the `t` alias

**Comment by andrewculver** [comment]
@domchristie I think that last example is OK, because the desired behavior of `t` is to pick up on whatever context it's being executed in, so I think most developers would understand if that prefixed the key with the path of the view `t` was evaluated within (in this case, the _calling_ partial).

**Comment by andrewculver** [comment]
I did, however, run into a problem with my solution. Given:

`app/views/account/scaffolding/completely_concrete/tangible_things/edit.html.erb`:

```
<%= render 'account/shared/page', title: t('.section') do |p| %>
  <% p.content_for :body do %>
    <%= render 'account/shared/box', divider: true do |p| %>
      <% p.content_for :title do %>
        <%= t('.header') %>
      <% end %>

      <% p.content_for :description do %>
        <%= t('.description') %>
      <% end %>

      <% p.content_for :body do %>
        <%= render 'form', tangible_thing: @tangible_thing %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
```

And given:

`app/views/account/scaffolding/completely_concrete/tangible_things/_form.html.erb`:

```
<%= form_with(model: tangible_thing, url: (tangible_thing.persisted? ? [:account, tangible_thing] : [:account, @absolutely_abstract_creative_concept, :completely_concrete_tangible_things]), local: true) do |form| %>
  <%= render 'account/shared/forms/errors', form: form %>
  <%= render 'shared/fields/text_field', form: form, method: :text_field_value, options: {autofocus: true} %>
  <div class="buttons">
    <%= form.submit (form.object.persisted? ? t('.buttons.update') : t('.buttons.create')), class: "button" %>
    <%= link_to t('global.buttons.cancel'), (form.object.persisted? ? [:account, tangible_thing] : [:account, @absolutely_abstract_creative_concept, :completely_concrete_tangible_things]), class: "button-secondary" %>
  </div>
<% end %>
```

In that situation, `t('.buttons.update')` should produce a locale key of `account.scaffolding.completely_concrete.tangible_things.form.buttons.update`, but with Nice Partials current implementation it's producing `en.account.scaffolding.completely_concrete.tangible_things.edit.buttons.update`.

This is because the current approach is just going up the stack trace to try and determine where `content_for` was invoked, but it's actually wrong in this case, because the original calling partial is actually delegating to a nested partial. Whatever approach we take needs to take _that_ into account.

**Comment by domchristie** [comment]
> @domchristie I think that last example is OK, because the desired behavior of `t` is to pick up on whatever context it's being executed in, so I think most developers would understand if that prefixed the key with the path of the view `t` was evaluated within (in this case, the _calling_ partial).

I dunno. I think it's a bit strange that:

```erb
<% p.content_for :heading, t(.greeting) %>
```

 works differently to:

```erb
<% p.content_for :heading do %>
  <%= t(.greeting) %>
<% end %>
```

The second one gets the "magic" by being executed in the block context, whereas the first does not :/

**Comment by andrewculver** [comment]
Hmm... I think the theory those should produce the same result, because even in the first example it's not being executed until <% yield p = np %> in the child partial, no? 🤔

**Comment by andrewculver** [comment]
Hmm... yes, you're right. Both of those should do the same thing.

**Comment by andrewculver** [comment]
Can't wait to get a test suite together for all these edge cases. 🥵

**Comment by domchristie** [comment]
Perhaps this could be achieved by performing the prefixing once NicePartial::Partial has been instantiated rather than on content_for?

**Comment by andrewculver** [comment]
@domchristie I figured it out! I've got the last use case you mentioned fixed! The solution was to not only wrap the `content_for` calls, but also calls to `render` (which was a little tricker, since I couldn't do that with a helper). However, with this, it seems to work exactly as I'd hope based on how people normally expect `t(".example")` to work.

**Comment by andrewculver** [comment]
And pushed up one final commit for this that fixes the use case I noted was broken!

**Pull request merged**
