### PR TITLE
Custom content sections

### PR DESCRIPTION
**Pull request by kaspth**
This adds a layer on top `NicePartial::Partial`s `content_for` API to have custom named sections and storing more than just string content. A slightly different take to https://github.com/bullet-train-co/nice_partials/pull/9

Here we define a `title` content section with some options that we can then refer to later and use to build other content:

```ruby
<%= yield p = np %>
<% p.title class: "some-class", data: { controller: "yup" } %>
<%= tag.span **p.title.options %>
```

With this abstraction we could potentially also allow merging two `NicePartial::Partial`s to allow for https://github.com/bullet-train-co/nice_partials/issues/11, so delegation really becomes copy the passed in sections to the new `NicePartial::Partial` or something like that.

Also curious what @domchristie and @seanpdoyle thinks of something like this, since they've done a lot of work in this area.

### CODE REVIEW

**Comment by domchristie** [comment]
Just having a play with this now. Is there a new API for setting content? I have a card partial (as above) and a template that renders it:

```erb
<%= render "card" do |card| %>
  <% card.content_for :title, "Hello, world!" %>
<% end %>
```

but this just renders:

```html
<span class="some-class" data-controller="yup"></span>
```

`p.title.inspect`:

```
 #<NicePartials::Partial::Section:0x00000001239f6c20 @content="", @options={:class=>"some-class", :data=>{:controller=>"yup"}}> 
```

**Comment by kaspth** [comment]
@domchristie yeah, the card template I showed doesn't render an element, it just render some options because I wanted to showcase the difference. `<%= tag.h1(p.title, p.title.options) %>` would be how to render the element (but there's also no `title` content defined in that template).

**Comment by domchristie** [comment]
I think this also changes the `content_for` behaviour to be more like [`provide`](https://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html#method-i-provide). Might be unusual to do this…

**Before**
```erb
<%= render "card" do |card| %>
  <% card.content_for :title, "Hello" %>
  <% card.content_for :title, "world" %>

  <%= card.content_for :title # Helloworld %>
<% end %>
```

**After**
```erb
<%= render "card" do |card| %>
  <% card.content_for :title, "Hello" %>
  <% card.content_for :title, "world" %>

  <%= card.content_for :title # world %>
<% end %>
```

**Comment by kaspth** [comment]
@domchristie sure, good point. I was going off the README that used the `flush: true` examples and figured we didn't want to support appending to a section. Though I've extracted the first commit into #42 and fixed this so we're appending like `content_for` does.

**Comment by kaspth** [comment]
Closed in favor of #43 though there may be more parts we want to grab from here.

**Pull request closed without merging**
